Add Pytorch and Tensorflow Load Test code using odh manifests test iamge
red-hat-data-services/odh-operator-test-harness pull request #2
Opened 2021-03-12 18:16 UTC by Jooho

- Added logics to deploy Job object to test Pytorch and Tensorflow Load-Test using odh manifest test image
- Added Doc

2021-03-12 21:16 UTC, taneem-ibrahim commented
@crobby /PTAL

2021-03-24 18:59 UTC, crobby commented on Makefile
> +DEFAULT_REGISTRY_NAMESPACE=opendatahub
modh namespace

2021-03-25 14:01 UTC, Jooho commented on Makefile
> +DEFAULT_REGISTRY_NAMESPACE=opendatahub
updated

2021-05-03 18:12 UTC, crobby requested changes
Current JH tests not passing.  

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="ImageDropdownBtn"]"}
  (Session info: headless chrome=89.0.4389.90)

I believe that the UI has changed a bit, so there are likely some adaptations needed.

2021-05-03 18:12 UTC, crobby commented on docs/Jupyterhub_Load_Test.md
> +  Find a pushgateway url from shorturl.at/DQY49
This URL doesn't seem to be active anymore

2021-05-03 18:25 UTC, crobby commented
> Current JH tests not passing.
> 
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="ImageDropdownBtn"]"}
> (Session info: headless chrome=89.0.4389.90)
> 
> I believe that the UI has changed a bit, so there are likely some adaptations needed.

@Jooho You may also want to talk with @LaVLaS as he knows a lot about these tests.  He might also eventually be working on https://issues.redhat.com/browse/RHODS-646 which is related to updating the tests.

2021-05-03 19:26 UTC, crobby commented
Running make cluster-test also seems to be looking for the operator logs in the wrong namespace....

```
++ oc get pods -n redhat-ods-applications -l name=opendatahub-operator -o 'jsonpath={$.items[*].metadata.name}'
+ oc logs -n redhat-ods-applications
```
The operator runs in the redhat-ods-operator namespace

2021-09-08 16:39 UTC, Jooho commented
Plan changed. We don't test them with test harness so I close this PR

2021-09-08 16:39 UTC, closed without merging